# Data Exploratory Analysis

In [2]:
import pandas as pd
import seaborn as sns

In [3]:
label_col = "Label"

In [4]:
data = pd.read_csv("../data/train.csv")

In [5]:
data

,SNo,lat,lon,TMQ,U850,V850,UBOT,VBOT,QREFHT,PS,...,T200,T500,PRECT,TS,TREFHT,Z1000,Z200,ZBOT,time,Label
0,1,21.707953,275.0000,78.909431,-58.805229,36.200672,-58.260475,-0.722955,0.022321,97497.79688,...,227.119232,273.045563,1.390000e-05,302.350861,300.026764,66.339836,12400.22754,66.241585,20031024,1
1,2,21.707953,275.0000,78.909431,-58.805229,36.200672,-58.260475,-0.722955,0.022321,97497.79688,...,227.119232,273.045563,1.390000e-05,302.350861,300.026764,66.339836,12400.22754,66.241585,20031024,1
2,3,21.473272,275.0000,80.641357,-42.340290,58.060246,-56.400234,26.484743,0.022204,96611.60156,...,229.172897,273.580810,1.440000e-05,302.350861,299.798828,66.165573,12371.33203,66.165268,20031024,1
3,4,21.473272,275.0000,80.641357,-42.340290,58.060246,-56.400234,26.484743,0.022204,96611.60156,...,229.172897,273.580810,1.440000e-05,302.350861,299.798828,66.165573,12371.33203,66.165268,20031024,1
4,5,21.707953,275.3125,76.891205,-45.996342,42.691631,-48.993065,10.246445,0.022328,98168.55469,...,224.642563,272.152283,9.890000e-06,302.462708,300.160187,66.880089,12386.88574,66.275246,20031024,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44755,44756,13.494133,253.7500,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1
44756,44757,13.494133,253.7500,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,0
44757,44758,13.494133,253.7500,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1
44758,44759,13.494133,253.7500,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1
44759,44760,13.494133,253.7500,58.471558,26.397322,5.664860,30.215387,1.547393,0.021974,98739.55469,...,217.845352,272.109589,1.120000e-07,301.878662,300.574646,66.438522,12340.96973,66.438522,20011207,1

In [6]:
data.describe()

,SNo,lat,lon,TMQ,U850,V850,UBOT,VBOT,QREFHT,PS,...,T200,T500,PRECT,TS,TREFHT,Z1000,Z200,ZBOT,time,Label
count,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,...,44760.000000,44760.000000,4.476000e+04,44760.000000,44760.000000,44760.000000,44760.000000,44760.000000,4.476000e+04,44760.000000
mean,22380.500000,-2.933507,269.270833,34.621980,-0.609818,-0.017271,-2.138797,-0.808013,0.014375,101553.676510,...,216.829335,264.355844,4.580801e-08,298.344652,296.923570,135.521651,12290.118668,65.384474,2.001878e+07,0.387332
std,12921.243361,22.906771,41.046619,12.765972,6.866391,4.307206,6.059180,4.786933,0.003951,544.619301,...,2.295840,3.463063,2.448857e-07,3.763268,3.998874,42.355824,129.311333,1.035777,3.169958e+04,0.764119
min,1.000000,-31.095176,229.062500,6.960679,-58.805229,-26.216906,-58.260475,-20.760452,0.004364,96611.601560,...,208.824249,249.146011,-4.400000e-23,289.330750,285.426666,63.335205,11718.249020,62.433594,1.996061e+07,0.000000
25%,11190.750000,-24.582790,241.875000,23.906342,-5.520361,-2.379751,-6.568208,-3.897676,0.011261,101161.437500,...,215.463791,262.966995,1.410000e-14,295.959228,294.304199,102.716108,12230.382810,64.672365,2.000091e+07,0.000000
50%,22380.500000,-3.872229,253.125000,34.779505,-1.707679,0.148625,-2.701227,-0.855717,0.014613,101528.492200,...,217.109589,265.177933,5.210000e-09,298.752502,297.352692,133.820953,12319.832030,65.482857,2.001093e+07,0.000000
75%,33570.250000,21.766623,277.187500,44.321056,3.546206,2.326534,1.663309,2.034851,0.017949,101873.328100,...,218.367691,266.811386,3.030000e-08,301.767212,300.476807,161.562851,12388.112300,66.329466,2.003072e+07,0.000000
max,44760.000000,24.054759,354.375000,80.641357,32.277344,58.060246,30.215387,31.106283,0.022366,103996.953100,...,229.172897,273.580810,1.440000e-05,303.869812,304.364197,328.123688,12495.289060,67.131653,2.009102e+07,2.000000

In [9]:
data.Label.value_counts(normalize=True)

0    0.785947
2    0.173280
1    0.040773
Name: Label, dtype: float64